export enum Querykeys {
  USER_PROFILE = "USER_PROFILE",
  VIEW_SUBJECTS = "VIEW_SUBJECTS",
  VIEW_CONTENTS = "VIEW_CONTENTS",
  VIEW_TESTS = "VIEW_TESTS",
  VIEW_TUTORIAL_CENTER = "VIEW_TUTORIAL_CENTER",
  VIEW_EXAM_TYPES = "VIEW_EXAM_TYPES",
  VIEW_FAVORITES = "VIEW_FAVORITES",
  VIEW_PROFILE = "VIEW_PROFILE",
  SUGGESTED_CONTENTS = "SUGGESTED_CONTENTS",
  VIEW_ROOMS = "VIEW_ROOMS",
  VIEW_MESSAGES = "VIEW_MESSAGES",
}
